# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_usuario_telf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='dummy@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
