# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20160528_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to=None)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Usuario')),
            ],
        ),
    ]
